marks = []
m1 = input("Enter Number :")
marks.append(m1)
m2 = input("Enter Number :")
marks.append(m2)
m3 = input("Enter Number :")
marks.append(m3)
m4 = input("Enter Number :")
marks.append(m4)
m5 = input("Enter Number :")
marks.append(m5)
m6 = input("Enter Number :")
marks.append(m6)
marks.sort()
print(marks)